import pygame

#화면
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

#미로관련
GRID_SIZE = 35       
TILE_SIZE = 20        
GRID_OFFSET_X = (SCREEN_WIDTH - (GRID_SIZE * TILE_SIZE)) // 2
GRID_OFFSET_Y = (SCREEN_HEIGHT - (GRID_SIZE * TILE_SIZE)) // 2

#플레이어
MOVE_COOLDOWN = 5
back_MOVE_COOLDOWN=3

#타일
WALL = 1
PATH = 0
IRON_GATE = 12
BROKEN = 13

#폰트
FONT_NAME='둥근모꼴regular'
BASE_FONT_SIZE=30
TIMER_FONT_SIZE = 50


#색상
COLOR_FINISH_ACTIVE = (0, 255, 0)
COLOR_FINISH_INACTIVE = (255, 0, 0)

#타이머
TOTAL_GAME_TIME_SECONDS = 5 * 60  # 5분

#압력
PSI_FONT_SIZE = 35
PULSATE_MAX_OFFSET = 10
PULSATE_SPEED = 0.005
PRESSURE_UPDATE_INTERVAL = 200   #0.2초마다 압력 미세 변화
MIN_RANDOM_CHANGE = 1 #기본 변동 압력 1~3
MAX_RANDOM_CHANGE = 3
MIN_SPIKE_INTERVAL = 3000  #급변 3~5초
MAX_SPIKE_INTERVAL = 5000   
MIN_SPIKE_CHANGE = 10 #급변 압력 10~30
MAX_SPIKE_CHANGE = 30

FPS=40
GATE_TOGGLE_INTERVAL = 120
BROKEN_TOGGLE_INTERVAL = 100
last_broken_stage = 0

#HP관련
MAX_HP=100
start_HP=100
HP_BAR_W=200
HP_BAR_H=20
HP_BAR_X=SCREEN_WIDTH-HP_BAR_W-20
HP_BAR_Y=750